apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
spec:
  dnsNames: 
   - "acme-test-0c743dbb.assistant-dev.peterhansen.io"
  secretName: test-tls-certificate
  issuerRef:
    name: "default-certificate-issuer"
    kind: ClusterIssuer
